apiVersion: v1
kind: Service
metadata:
  name: node-nosql-service
  labels:
    name: node-nosql-service
    app: node-nosql-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: node-nosql-app-pod
    app: node-nosql-app
